#!/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'rucio==1.17.7','console_scripts','rucio-light-reaper'
__requires__ = 'rucio==1.17.7'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rucio==1.17.7', 'console_scripts', 'rucio-light-reaper')()
    )
