sudo: required

language: python

services:
  - docker

install:
  - git diff --name-status HEAD $(git merge-base HEAD master) | grep \.py$ | grep -v '^A' | grep -v 'conf.py' | cut -f 2 | paste -sd " " - > changed_files.txt
  - cp etc/docker/travis/Dockerfile Dockerfile
  - docker build -t rucio/rucio .

before_script:
  - ./tools/travis_before_script.sh

script:
  - docker exec -it rucio /bin/sh -c "tools/travis_scripts.sh $TEST_ENV"

# after_script:
#  - ./tools/travis_after_script.sh

env:
  matrix:
    - TEST_ENV=flake8-pylint
    - TEST_ENV=oracle
    - TEST_ENV=mysql
    - TEST_ENV=postgres

#jobs:
#  include:
#    - stage: build docker image
#      script:
#      - git diff --name-status HEAD $(git merge-base HEAD master) | grep \.py$ | grep -v '^A' | grep -v 'conf.py' | cut -f 2 | paste -sd " " - > changed_files.txt
#      - cp etc/docker/travis/Dockerfile Dockerfile
#      - docker build -t rucio/rucio .
#      - docker tag rucio/rucio rucio/rucio:latest
#    - stage: test
#      script:
#      - docker run -d --name=rucio rucio/rucio
#      - docker exec -it rucio /bin/sh -c "tools/travis_scripts.sh flake8"

notifications:
  slack:
    secure: n8nmTHao0omraqNbqXsbv+0IqYyXDFYLZFYDuD9fXBz8nyD/U6mOqcYzlozsfA3vmVQI0qXfCohK9+CKRfWLFg7LhFZk0CeApU+YurXNdBFXdZDrY6kKQah/W56Fmw8hvfo0iMRar0pzRa7LPLDR+ZMrQUfQFUebM4pIa3wbzyUkzH1iPqtOB5FsHkJijHjBRShvWWRvlpiobQxgLBUWPGPpiOdBlnOTzzmEjIsjTXBPCgDjMEe/kqiJ4NHtWgOi5WTYxPlm5pv511TMXx23S+Uy5GrO1FAwqR/41yV5i/wxMdb8UGro+aT8SWkU8jBaQ7eQAnwhL88J3KTBeMeA2or5quu9bve0bpGSqu69n90CZyPhuudBJtusW6Bk76uO0bw1EdB9bJyCS9oA8mmn1qyQAwrOmR6203RczTyfIGMa90fIe4VMQNfmLMYlp1rx3U3DdajBfq6M/anmu2veJI1DyLzbgJz5AsgwuJhKTgQTSjOceSlqTe/dypLsKRpdj48gbvhUbPfx1q7R0yl+dNWpbUaR3fqtkp5f/R6KJTLlCzF7gRpGgfILhcqtHMxUtdWovQCnmbmgcX0JW2x416eGPSriADZKj9hDBW8Lo4BK5CONQ5VRitzNY3pVplHfI5uLjoKHuV+T/BZ7V6hzobmhBMBQUE2/xYe9bJtRfrQ=


