sudo: required

language: bash

services:
  - docker

install:
  - cp etc/docker/travis/Dockerfile Dockerfile
  - docker build -t rucio/rucio .

before_script:
  - docker run -d -p 8080:8080 -p 1521:1521 --name=oracle -e processes=1000 -e sessions=1105 -e transactions=1215 -e ORACLE_ALLOW_REMOTE=true sath89/oracle-xe-11g
  - docker run --name=activemq -d webcenter/activemq:latest
  - sleep 150
  - docker run -d --link oracle:oracle --link activemq:activemq --name=rucio rucio/rucio
  - docker ps -a

script:
  - docker exec -it rucio /bin/sh -c "tools/travis_scripts.sh"

after_script:
  - docker stop rucio
  - docker stop oracle
  - docker stop activemq
