# Copyright 2017-2018 CERN for the benefit of the ATLAS collaboration.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Thomas Beermann <thomas.beermann@cern.ch>, 2017-2018
# - Vincent Garonne <vgaronne@gmail.com>, 2017-2018
# - Mario Lassnig <mario.lassnig@cern.ch>, 2018

sudo: required

os:
  - linux

language: python

python:
  - 2.6
  - 2.7
  - 3.5
  - 3.6

services:
  - docker

install:
  - git diff --name-status HEAD $(git merge-base HEAD master) | grep \.py$ | grep -v '^A' | grep -v 'conf.py' | cut -f 2 | paste -sd " " - > changed_files.txt
  - python --version
  - pip --version
  - tools/travis/install_script.sh

before_script:
  - tools/travis/before_script.sh
  - docker ps -a

script:
  - if [[ $SUITE == "syntax" ]]; then ./tools/travis/check_syntax.sh  ; fi
  - if [[ $SUITE == "client"  && "$TRAVIS_PYTHON_VERSION" !=  "3.6"  ]]; then nosetests -v lib/rucio/tests/test_clients.py; fi
  - if [[ $SUITE == "client"  && "$TRAVIS_PYTHON_VERSION" ==  "3.6"  ]]; then nosetests -v lib/rucio/tests/test_clients.py; nosetests -v lib/rucio/tests/test_bin_rucio.py ; fi
  - if [[ $SUITE == "all" ]]; then docker exec -it rucio /bin/sh -c "/opt/rucio/tools/run_tests_docker.sh -1q" ; fi

env:
    - SUITE=all RDBMS=oracle
    - SUITE=all RDBMS=mysql
    - SUITE=all RDBMS=postgres
    - SUITE=all RDBMS=sqlite
    - SUITE=client RDBMS=sqlite RUCIO_HOME=`pwd`
    - SUITE=syntax

matrix:
  fast_finish: true
  exclude:
  - python: 2.6
    env: SUITE=all RDBMS=oracle
  - python: 2.6
    env: SUITE=all RDBMS=mysql
  - python: 2.6
    env: SUITE=all RDBMS=postgres
  - python: 2.6
    env: SUITE=all RDBMS=sqlite
  - python: 2.6
    env: SUITE=syntax
  - python: 3.4
    env:  SUITE=all RDBMS=oracle
  - python: 3.4
    env:  SUITE=all RDBMS=mysql
  - python: 3.4
    env:  SUITE=all RDBMS=postgres
  - python: 3.4
    env:  SUITE=all RDBMS=sqlite
  - python: 3.4
    env: SUITE=syntax
  - python: 3.5
    env: SUITE=syntax
  - python: 3.5
    env:  SUITE=all RDBMS=oracle
  - python: 3.5
    env:  SUITE=all RDBMS=mysql
  - python: 3.5
    env:  SUITE=all RDBMS=postgres
  - python: 3.5
    env:  SUITE=all RDBMS=sqlite
  - python: 3.6
    env: SUITE=all
  - python: 3.5
    env:  SUITE=all RDBMS=oracle
  - python: 3.5
    env:  SUITE=all RDBMS=mysql
  - python: 3.5
    env:  SUITE=all RDBMS=postgres
  - python: 3.5
    env:  SUITE=all RDBMS=sqlite
  - python: 3.6
    env:  SUITE=all RDBMS=oracle
  - python: 3.6
    env:  SUITE=all RDBMS=mysql
  - python: 3.6
    env:  SUITE=all RDBMS=postgres
  - python: 3.6
    env:  SUITE=all RDBMS=sqlite
  allow_failures:
  - python: 3.6
    env: SUITE=syntax
  - python: 3.6
    env: SUITE=client RDBMS=sqlite RUCIO_HOME=`pwd`


notifications:
  slack:
    secure: n8nmTHao0omraqNbqXsbv+0IqYyXDFYLZFYDuD9fXBz8nyD/U6mOqcYzlozsfA3vmVQI0qXfCohK9+CKRfWLFg7LhFZk0CeApU+YurXNdBFXdZDrY6kKQah/W56Fmw8hvfo0iMRar0pzRa7LPLDR+ZMrQUfQFUebM4pIa3wbzyUkzH1iPqtOB5FsHkJijHjBRShvWWRvlpiobQxgLBUWPGPpiOdBlnOTzzmEjIsjTXBPCgDjMEe/kqiJ4NHtWgOi5WTYxPlm5pv511TMXx23S+Uy5GrO1FAwqR/41yV5i/wxMdb8UGro+aT8SWkU8jBaQ7eQAnwhL88J3KTBeMeA2or5quu9bve0bpGSqu69n90CZyPhuudBJtusW6Bk76uO0bw1EdB9bJyCS9oA8mmn1qyQAwrOmR6203RczTyfIGMa90fIe4VMQNfmLMYlp1rx3U3DdajBfq6M/anmu2veJI1DyLzbgJz5AsgwuJhKTgQTSjOceSlqTe/dypLsKRpdj48gbvhUbPfx1q7R0yl+dNWpbUaR3fqtkp5f/R6KJTLlCzF7gRpGgfILhcqtHMxUtdWovQCnmbmgcX0JW2x416eGPSriADZKj9hDBW8Lo4BK5CONQ5VRitzNY3pVplHfI5uLjoKHuV+T/BZ7V6hzobmhBMBQUE2/xYe9bJtRfrQ=
