sudo: required

language: bash

services:
  - docker

install:
  - cp etc/docker/travis/Dockerfile Dockerfile
  - git diff --name-status HEAD $(git merge-base HEAD master) | grep .py | grep -v '^A' |  grep -v 'conf.py' | cut -f 2 | paste -sd " " - > changed_files.txt
  - docker build -t rucio/rucio .

before_script:
  - docker run -d -p 8080:8080 -p 1521:1521 --name=oracle -e processes=1000 -e sessions=1105 -e transactions=1215 -e ORACLE_ALLOW_REMOTE=true sath89/oracle-xe-11g
  - docker run --name=mysql -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_ROOT_HOST=% -d mysql/mysql-server:5.7
  - docker run --name=postgres -e POSTGRES_PASSWORD=secret -d postgres
  - docker run --name=activemq -d webcenter/activemq:latest
  - sleep 150
  - docker run -d --link oracle:oracle --link mysql:mysql --link postgres:postgres --link activemq:activemq --name=rucio rucio/rucio
  - docker ps -a

script:
  - docker exec -it rucio /bin/sh -c "tools/travis_scripts.sh"

after_script:
  - docker stop rucio
  - docker stop oracle
  - docker stop mysql
  - docker stop postgres
  - docker stop activemq
