name: dev

services:
  rucio:
    build:
      context: ../../../
      dockerfile: etc/docker/test/runtime.Dockerfile
      args:
        PYTHON: ${PYTHON:-3.9}
    image: ${RUCIO_TEST_IMAGE:-rucio-test:local}
    environment:
      - RDBMS
      - RUCIO_HOME=/opt/rucio
      - PYTEST_DISABLE_PLUGIN_AUTOLOAD=True

  ruciodb:
    profiles:
      - donotstart
