input {
  jms {
    broker_url => "tcp://activemq:61616"
    destination => "events"
    factory => "org.apache.activemq.ActiveMQConnectionFactory"
    type => "rucio-event"
    codec => "json"
    # Needs to match the download path in logstash/entrypoint.sh
    require_jars => ["/usr/share/logstash/data/jars/activemq-all-${ACTIVEMQ_VERSION}.jar"]
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch"
    index => "rucio-events-%{+YYYY.MM.dd}"
  }
}
