#!/usr/bin/env python
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Cedric Serfon, <cedric.serfon@cern.ch>, 2014
#
import sys
from rucio.client import Client

if __name__ == "__main__":
    host = sys.argv[1]
    # print 'Ping %s' % host
    c = Client(rucio_host='https://%s' % host)
    print 'Rucio version installed : %s ' % c.ping()['version']
