#!/usr/bin/env python
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Vincent Garonne, <vincent.garonne@cern.ch>, 2013

'''
Probe to check the backlog of expired rules.
'''
import sys
import traceback

from rucio.core import monitor
from rucio.db.sqla.session import get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == "__main__":
    try:
        session = get_session()
        result = session.execute('select count(1) from atlas_rucio.rules where expires_at < sys_extract_utc(localtimestamp)').fetchone()[0]
        monitor.record_gauge(stat='judge.expired_rules', value=result)
        result = session.execute('select count(1) from atlas_rucio.rules where expires_at > sys_extract_utc(localtimestamp)').fetchone()[0]
        monitor.record_gauge(stat='judge.lifetimed_rules', value=result)
        print result
    except:
        print traceback.format_exc()
        sys.exit(UNKNOWN)
    sys.exit(OK)
