#!/usr/bin/env python
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Martin Barisits, <martin.barisits@cern.ch>, 2015

'''
Probe to repair rule heatlh of tzero rules
'''

import sys
from rucio.db.session import get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

def main():
    '''
    Probe to repair rule health
    '''
    try:
        session = get_session()
        query = '''DECLARE
content_cnt NUMBER;
lock_cnt NUMBER;
BEGIN
    for r in (SELECT /*+ FULL(rules) parallel(4) */ ru.scope, ru.name, ru.id, ru.copies, ru.rse_expression FROM ATLAS_RUCIO.rules ru, ATLAS_RUCIO.dids di WHERE ru.did_type='D' and
        ru.state='O' and
        ru.updated_at < sys_extract_utc(localtimestamp)-2/24 and
        (ru.expires_at IS NULL or ru.expires_at > sys_extract_utc(localtimestamp)+4/24) and
        di.scope = ru.scope and
        di.name = ru.name and
        (di.expired_at IS NULL or di.expired_at > sys_extract_utc(localtimestamp)+4/24) and
        ru.account = 'tzero'
        ORDER by ru.created_at ASC)
    loop
        SELECT count(*) INTO content_cnt FROM ATLAS_RUCIO.contents c WHERE c.scope=r.scope and c.name=r.name;
        SELECT count(*) INTO lock_cnt FROM ATLAS_RUCIO.locks WHERE rule_id=r.id;
        IF content_cnt * r.copies != lock_cnt THEN
            UPDATE ATLAS_RUCIO.rules SET state = 'S' WHERE id = r.id;
            COMMIT;
        END IF;
    end loop;
END;'''
        session.execute(query)
    except Exception, e:
        sys.exit(UNKNOWN)
    sys.exit(OK)

if __name__ == "__main__":
    main()
