server {
    listen 443 ssl;
    server_name localhost garage garage.default.svc.cluster.local;

    ssl_certificate /etc/nginx/garage.cert.pem;
    ssl_certificate_key /etc/nginx/garage.key.pem;

    location / {
        client_max_body_size 5G;

        proxy_pass http://garage1:3900;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
