apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: ingress-traefik-backend
  name: ingress-traefik
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ingress-traefik-backend
      name: ingress-traefik-backend
  template:
    metadata:
      labels:
        k8s-app: ingress-traefik-backend
        name: ingress-traefik-backend
    spec:
      containers:
      - args:
        - --web
        - --configFile=/config/traefik.toml
        - --kubernetes
        image: gitlab-registry.cern.ch/cloud/atomic-system-containers/traefik
        imagePullPolicy: Always
        name: ingress-traefik-backend
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: admin
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: ssl
          name: ssl
        - mountPath: config
          name: config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        role: ingress
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ingress-traefik
      serviceAccountName: ingress-traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          defaultMode: 420
          secretName: traefik-secret
      - configMap:
          defaultMode: 420
          name: traefik-conf
        name: config
  templateGeneration: 3
  updateStrategy:
    type: OnDelete
