globus:
  apps:
    accounts:
      cgamboa:
        client_id: 1234
        refresh_token: 4321
      msnyder:
        client_id: 5678
        refresh_token: 8765
    SDK Tutorial App:
      client_id: 02836fea-22df-48d0-99a5-13510916c88f
      refresh_token: Ag245GQwjQvGzxNwwX8586WWMblMxab2M6zE2ox4Y21Kp96vkntMUqvVDb3jkq82vDWMpGJnbVnpx1JgOyN9anq7qjvDJ
      source_endpoint_id: 76eaadbc-36d6-11e9-9838-0262a1f2f698
      destination_endpoint_id: aa0743e4-44d8-11e9-a618-0a54e005f950
      sdccfed_endpoint_id: 23f78cc8-41e0-11e9-a618-0a54e005f950
      win10_endpoint_id: aa0743e4-44d8-11e9-a618-0a54e005f950
    RucioGlobusTest:
      client_id: 05188d5e-e1d6-4aee-b664-cbb5a44d5399
      client_secret: WzmlINCxzfTpPztzqIn90CRP1FdzMDXJp371KGY3rM8=
    RucioGlobusBNLNativeApp:
      client_id: 7a478e09-5c7d-4778-81eb-548e61ab3200
      access_token: Aggdwg60l3oJWdX0beek5aEwKEOonxPzWr1X781MjXo0eWp4wKhJClWyjOyp4EXg3dyzy58dzB1nqlH19yEa9cWwB8-
      refresh_token: AgjoJj7WvnxmDq2NGd6g7ogeddqG80Wd0j17NOk2bYdpWGkNnlfKUgWJD7ardvrX7pMx2bPjb43XjWDeywVGYzx45g7bj
    BlueskyAuthApp:
      client_id: 837abac5-f20e-4ca7-96a1-2a625da8f256
      refresh_token: AgmxjO2gyoN2W0j1WkX1EOMVyKBGpxy1vYv0ykkrkBgPdoo54zSDUjp1Qp1a9E0QOb5X0GK3ovr2BOqgp2g1mEnXOD1mV
    BlueskyAuthApp2:
      client_id: a9e1434c-dcc5-4c98-8291-c251dba3eac3
      refresh_token: AgEgQK9y9qrwaQv2yydpgvKv77O0aB8GnrmyKNKWeePBkljPEkfbUg1WX8zPMBJb6kVbBmdXpGBN2QJNrd2WGy4qwWxEK
    nsls2-rucio:
      client_id: 7ac499a7-b4c9-46fd-a895-ad096d89b514
      refresh_token: Ag2Vb3d3BgNGKnYkkrb1eaJezm8MnDeOW9NEm4meV3BvK4lPY2hMUD3EkgmMv8WWdYJyMPOzwNvBMP8aNe8MqgXjv6mQp
