
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '37.1.0.post1',
    'branch_nick': 'release-37',
    'revision_id': '420fea7843ab9f55e21b71eb93709f7621db8873',
    'revno': 13642
}
