
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.14.8',
    'branch_nick': 'patch-0-1_14_8_preparation',
    'revision_id': 'a4ef2f5cc53991862d6e2efc0970ec45ff70c7d4',
    'revno': 5846
}
