apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rucio.fullname" . }}-auth-aliases
  labels:
    app: {{ template "rucio.fullname" . }}-auth
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  aliases.conf: |+
    WSGIScriptAlias /auth /usr/lib/python2.7/site-packages/rucio/web/rest/authentication.py
    WSGIScriptAlias /ping /usr/lib/python2.7/site-packages/rucio/web/rest/ping.py
