{{- if .Values.authIngress.enabled -}}
{{- $fullName := include "rucio.fullname" . -}}
{{- $ingressPath := .Values.authIngress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-auth
  labels:
    app: {{ template "rucio.name" . }}-auth
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.authIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.authIngress.tls }}
  tls:
  {{- range .Values.authIngress.tls }}
    - hosts:
      {{- range $.Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.authIngress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-auth
              servicePort: http
  {{- end }}
{{- end }}
