#!/usr/bin/env python

# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Vincent Garonne, <vincent.garonne@cern.ch>, 2016

"""
Script to check space usage json file
"""

from jsonschema import validate

import json, sys

if __name__ == '__main__':

    with open('space-usage-schema.json') as schema_file:
        schema = json.load(schema_file)

    with open(sys.argv[1]) as space_usage_file:
        space_usage = json.load(space_usage_file)

    validate(space_usage, schema)
