apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
      - name: config-volume
        secret:
          secretName: server-cfg
      containers:
        - name: server
          image: rucio/rucio-server:release-1.16.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: RUCIO_ENABLE_SSL
              value: "False"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
          volumeMounts:
          - name: config-volume
            readOnly: false
            mountPath: "/opt/rucio/etc/rucio.cfg"
            subPath: "rucio.cfg"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: server
  selector:
    app: server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-front
  annotations:
    traefik.frontend.entryPoints: https
    passHostHeader: true
spec:
  rules:
    - host: "*.cern.ch"
      http:
        paths:
          - path: /
            backend:
              serviceName: server
              servicePort: 80
