apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash-oss:6.2.4
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: pipeline-volume
            mountPath: /usr/share/logstash/pipeline
          - name: cacert
            mountPath: /etc/pki/tls/certs
            readOnly: true
      volumes:
      - name: pipeline-volume
        secret:
          secretName: logstash-pipeline
      - name: cacert
        secret:
          secretName: cern-bundle
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: kube-system
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    name: logstash
  type: NodePort
