#!/bin/sh

MSG="$1"

# Test if a JIRA ticket is associated with the commit msg
if ! grep '^\[RUCIO-' "$MSG" >/dev/null
then
    echo "No JIRA ticket(s) is/are associated with the commit msg!"
    exit 1
fi
