#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo 'usage: tools/create-patch-branch <ticketnumber> <branchname>'
    echo
    echo 'examples: tools/create-patch-branch 1234 fancypatch'
    echo '          tools/create-patch-branch 1234 "my fancy patch"'
    exit 1
fi

echo "Switching to master"
git checkout master

echo "Updating master"
git pull --all --prune --progress

echo "Rebasing master"
git reset --hard upstream/master
if [ $? != 0 ]; then
    echo "Can't rebase to master. Unstaged changes?"
    exit 1
fi

echo "Creating patch branch"
git checkout -b patch-$1-${2//[^a-zA-Z0-9]/_} master

echo "Done"
