#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo 'usage: tools/create-feature-branch <ticketnumber> <branchname>'
    echo
    echo 'examples: tools/create-feature-branch 1234 fancyfeature'
    echo '          tools/create-feature-branch 1234 "my fancy feature"'
    exit 1
fi

echo "Fetching upstream"
git fetch upstream --progress

echo "Switching to master"
git checkout upstream/master -B master
if [ $? != 0 ]; then
    echo "Can't reset and checkout master"
    exit 1
fi

echo "Creating feature branch from master"
git checkout -b feature-$1-${2//[^a-zA-Z0-9]/_} master

echo "Done"
