#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright European Organization for Nuclear Research (CERN) since 2012
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ $# -ne 2 ]] ; then
    echo 'usage: tools/create-feature-branch <ticketnumber> <branchname>'
    echo
    echo 'examples: tools/create-feature-branch 1234 fancyfeature'
    echo '          tools/create-feature-branch 1234 "my fancy feature"'
    exit 1
fi

echo "Fetching upstream"
git fetch upstream --progress

echo "Switching to master"
git checkout upstream/master -B master
if [ $? != 0 ]; then
    echo "Can't reset and checkout master"
    exit 1
fi

echo "Creating feature branch from master"
git checkout -b feature-$1-${2//[^a-zA-Z0-9]/_} master

echo "Done"
