#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright European Organization for Nuclear Research (CERN) since 2012
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NUMBER=$(git branch | grep '*' | grep 'patch\|feature\|hotfix' | cut -d- -f2)
if [ -z $NUMBER ]
then
    echo "Not a patch or feature or hotfix branch"
else
    EDITMSG=$(cat $1)
    if echo $EDITMSG | grep "# Please enter the commit message for your changes.*"
    then
	echo "No commit message given, preparing template for editing."
	sed -i "1s/^/\#\<component\>: \<message\>; Fix \#$NUMBER\n/" $1
    else
	echo "Using CLI commit message."
    fi
fi
