#!/usr/bin/env python
#
# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Martin Barisits, <martin.barisits@cern.ch>, 2017


import commands
import sys
import requests
import json

requests.packages.urllib3.disable_warnings()


def submit_pull_request(user, current_branch, target_branch, message, label):
    data = {'title': message,
            'head': '%s:%s' % (user, current_branch),
            'base': target_branch}

    r = requests.post(url='https://api.github.com/user/repos/%s/rucio/pulls' % user,
                      params={'access_token': github_token},
                      data=data)
    if r.status_code == 200:
        return True
    return False


root_git_dir = commands.getstatusoutput('git rev-parse --show-toplevel')[1]

# Load OAUTH token
print 'Loading github OAUTH token ...',
try:
    with open(root_git_dir + '/.githubtoken', 'r') as f:
        github_token = f.readline().strip()
        print 'OK'
except:
    print 'ERROR'
    print 'No github token file found at %s' % root_git_dir + '/.githubtoken'
    sys.exit(-1)

# Get the current GitHub user
r = requests.get(url='https://api.github.com/user',
                 params={'access_token': github_token})
user = json.loads(r.text)['login']

# Check if current branch is not master or next
print 'Checking if current branch is a patch/feature/hotfix branch ...',
current_branch = commands.getstatusoutput('git rev-parse --abbrev-ref HEAD')[1]
commit_msg = current_branch
for line in commands.getstatusoutput('git log -1')[1].splitlines():
    if line.strip().startswith('Author') or line.strip().startswith('Date') or line.strip().startswith('commit') or line.strip() == '':
        continue
    commit_msg = line.strip()
    break
if current_branch == 'master' or current_branch == 'next' or current_branch == 'hotfix':
    print 'ERROR'
    print 'You are currently on branch \'%s\'. Please change to a feature/patch/hotfix branch.' % current_branch
    sys.exit(-1)
if not current_branch.startswith('patch') and not current_branch.startswith('feature') and not current_branch.startswith('hotfix'):
    print 'ERROR'
    print 'You are currently on branch \'%s\'. This is not a feature/patch/hotfix branch.' % current_branch
    sys.exit(-1)
print 'OK'

# Get ticket number
ticket_nr = current_branch.split('-')[1]

# Get labels
if current_branch.startswith('feature'):
    label = 'feature'
elif current_branch.startswith('hotfix'):
    label = 'hotfix'
else:
    label = 'patch'

# Push the branch to origin
print 'Pushing the feature/patch/hotfix branch to origin ...',
op = commands.getstatusoutput('git push origin %s' % current_branch)
if op[0] == 0:
    print 'OK'
else:
    print 'ERROR'
    print op[1]
    sys.exit(-1)

# Create the Pull-requests
if current_branch.startswith('hotfix'):
    print 'Submitting merge request against hotfix ...',
    if submit_pull_request(user, current_branch, 'hotfix', commit_msg, label):
        print 'OK'
    else:
        print 'ERROR'

if current_branch.startswith('patch') or current_branch.startswith('hotfix'):
    print 'Submitting merge request against master ...',
    if submit_pull_request(user, current_branch, 'master', commit_msg, label):
        print 'OK'
    else:
        print 'ERROR'

# Submit against NEXT
print 'Submitting merge request against next ...',
if submit_pull_request(user, current_branch, 'next', commit_msg, label):
    print 'OK'
else:
    print 'ERROR'
