#!/bin/bash
#
# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Mario Lassnig (CERN PH-ADP), <mario.lassnig@cern.ch>, 2006-2011


usage() {
    echo "usage: submit-review [-h/--help] [-d/--dry] [-a/--amend <message>]"
    echo
    echo This submits the currently commited local master to gerrit for review.
    echo If you want to amend the previous commit, give the new amend commit message as an optional argument.
    echo
    echo Use the --dry run to validate without submitting.
    echo
    echo
    echo Examples
    echo --------
    echo
    echo To submit a new patch set: submit-review
    echo
    echo To amend an existing patch set: submit-review -a \"I fixed this now\"
    echo
    echo To test amend an existing patch set: submit-review -d -a \"I fixed this now\"
}

set_commit_msg() {
    git_dir=`git rev-parse --show-toplevel`
    to_be="${git_dir}/.git/hooks/commit-msg"
    to_get="https://svnweb.cern.ch/trac/dq2/raw-attachment/wiki/DQ2%20Developer%27s%20Corner/commit-msg"

    if [[ ! -e $to_be ]]; then
        echo "commit-msg does not exist, creating"
        curl $to_get > $to_be
        chmod +x $to_be
    fi
}

push_commit() {
    if [[ "$@" == *-a* ]]; then
        cid=`git log -1 | grep Change-Id: | awk '{print $2;}'`
        echo Amending previous commit with Change-Id: $cid and Comment: $BASH_ARGV
        $dry git commit -a --amend -m "$BASH_ARGV

Change-Id: $cid"
        if [ ! $? -eq 0 ] ; then
            echo "FATAL amend did not work! Aborting."
            exit 1
        fi
    fi
    $dry git push origin HEAD:refs/for/master
    if [ ! $? -eq 0 ] ; then
        echo "FATAL push did not work! Aborting."
        exit 2
    fi
}

main() {

    dry=""

    if [[ "$@" == *-d* ]]; then
        dry='echo '
    fi

    if [[ "$@" == *-h* ]]; then
        usage;
    else
        set_commit_msg;
        push_commit "$@";
    fi
}


main "$@"
