#!/bin/bash
#
# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Mario Lassnig (CERN PH-ADP), <mario.lassnig@cern.ch>, 2006-2011

usage() {
    echo "usage: submit-review [-h/--help] [-d/--dry] [-a/--amend <message>]"
    echo
    echo This submits the currently commited local master to gerrit for review.
    echo If you want to amend the previous commit, give the new amend commit message as an argument.
    echo
    echo Use the --dry run to validate without submitting.
    echo
    echo
    echo Examples
    echo --------
    echo
    echo To submit a new patch set: submit-review
    echo
    echo To amend an existing patch set: submit-review -a \"I fixed this now\"
    echo
    echo To test amend an existing patch set: submit-review -d -a \"I fixed this now\"
}

set_commit_msg() {
    git_dir=`git rev-parse --show-toplevel`
    to_be="${git_dir}/.git/hooks/commit-msg"
    to_get="https://svnweb.cern.ch/trac/dq2/raw-attachment/wiki/DQ2%20Developer%27s%20Corner/commit-msg"

    if [[ ! -e $to_be ]]; then
        echo "commit-msg does not exist, creating"
        curl $to_get > $to_be
        chmod +x $to_be
    fi
}

push_commit() {
    if [[ "$@" == *-a* ]]; then
        if [[ $BASH_ARGV == -a ]]; then
            echo You are missing the amend message, e.g.: tools/submit-review -a \"now it is fixed\"
            exit 2
        fi
        cmt=`git log -1 --pretty=oneline | cut -d" " -f1`
        msg=`git log -1 --pretty=oneline | cut -d" " -f2-`
        cid=`git log -1 | grep Change-Id: | awk '{print $2;}'`
        echo Amending commit $cmt
        $dry git commit --amend -m "$msg ; $BASH_ARGV

Change-Id: $cid"
        if [ ! $? -eq 0 ] ; then
            echo "FATAL! Amend did not work! Aborting."
            exit 1
        fi
    fi
    $dry git push origin HEAD:refs/for/master
    if [ ! $? -eq 0 ] ; then
        echo "FATAL! Push did not work! Aborting."
        exit 2
    fi
}

main() {

    dry=""

    branch="$(git branch 2>/dev/null | sed -e "/^\s/d" -e "s/^\*\s//")"
    if [[ "$branch" == "master" ]]; then
        echo 'You want to push a master commit, that is not good practice.'
        echo 'Create new local branch and switch to it. E.g.:'
        echo 'git checkout -b new_feature'
        echo 'Make the change there, and submit from the branch.'
        exit 1
    else

        if [[ "$@" == *-d* ]]; then
            dry='echo '
        fi

        if [[ "$@" == *-h* ]]; then
            usage;
        else
            set_commit_msg;
            push_commit "$@";
        fi
    fi
}


main "$@"
