name: Run all the autotests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build runtime images for tests
  runtime_images:
    if: github.event_name != 'schedule'
    name: Build Runtime Images
    uses: ./.github/workflows/runtime_images.yml
    permissions:
      contents: read
      packages: write
  setup:
    if: github.repository_owner == 'rucio' || github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Update pip
        run: python3 -m pip install -U pip setuptools
      - name: Install python requirements for matrix_parser.py
        run: python3 -m pip install -U PyYAML
      - name: Identify branch
        id: branch
        run: python3 tools/github/workflow/set_branch_output_env.py
      - name: Identify Matrix
        id: matrix
        run: |
          EVENT="${{ github.event_name }}"
          if [ $EVENT != 'schedule' ]; then
            echo "matrix=$(./tools/test/matrix_parser.py < ./etc/docker/test/matrix.yml)" >> $GITHUB_OUTPUT
          else
            echo "matrix=$(./tools/test/matrix_parser.py < ./etc/docker/test/matrix_nightly.yml)" >> $GITHUB_OUTPUT
          fi
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
      matrix: ${{ steps.matrix.outputs.matrix }}
  test:
    needs: [runtime_images, setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Set repository variable
        id: repo
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Build Python 3.9 image locally
        if: needs.runtime_images.outputs.build_locally == 'true' && matrix.cfg.PYTHON == '3.9'
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: etc/docker/test/runtime.Dockerfile
          target: final
          build-args: |
            PYTHON=3.9
          push: false
          tags: ${{ needs.runtime_images.outputs.py39_image }}
          outputs: type=docker
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repo }}/rucio-dev-runtime:py39-buildcache
        continue-on-error: false
      - name: Build Python 3.10 image locally
        if: needs.runtime_images.outputs.build_locally == 'true' && matrix.cfg.PYTHON == '3.10'
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: etc/docker/test/runtime.Dockerfile
          target: final
          build-args: |
            PYTHON=3.10
          push: false
          tags: ${{ needs.runtime_images.outputs.py310_image }}
          outputs: type=docker
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repo }}/rucio-dev-runtime:py310-buildcache
        continue-on-error: false
      - name: Run test with cfg
        env:
          PY39_RUNTIME_IMAGE: ${{ needs.runtime_images.outputs.py39_image }}
          PY310_RUNTIME_IMAGE: ${{ needs.runtime_images.outputs.py310_image }}
          BUILD_LOCALLY: ${{ needs.runtime_images.outputs.build_locally }}
        run: |
          echo '{"matrix": ${{ toJson(matrix.cfg) }}, "runtime_images": {"3.9": "${{ needs.runtime_images.outputs.py39_image }}", "3.10": "${{ needs.runtime_images.outputs.py310_image }}"}, "build_locally": "${{ needs.runtime_images.outputs.build_locally }}" }' | ./tools/test/run_tests.py
